//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Mvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_USER
    {
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
    
        public virtual APP_USER_ROLE APP_USER_ROLE { get; set; }
    }
}
