//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Mvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKMARK
    {
        public int BOOKMARK_ID { get; set; }
        public string BOOKMARK_NAME { get; set; }
        public string BOOKMARK_LINK { get; set; }
        public string BOOKMARK_LOGIN_ID { get; set; }
        public string BOOKMARK_LOGIN_PASSWORD { get; set; }
        public Nullable<int> BOOKMARK_CATEGORY_ID { get; set; }
    
        public virtual BOOKMARK_CATEGORY BOOKMARK_CATEGORY { get; set; }
    }
}
