//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Mvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_PHONE { get; set; }
        public Nullable<int> EMP_SALARY { get; set; }
        public System.DateTime EMP_HIRE_DATE { get; set; }
        public string EMP_GENDER { get; set; }
        public Nullable<int> EMP_PHOTO_ID { get; set; }
        public Nullable<bool> EMP_IS_ACTIVE { get; set; }
    
        public virtual EMPLOYEE_PHOTO EMPLOYEE_PHOTO { get; set; }
    }
}
